### ISSUE TITLE
BUG: missing language for a movie

### ISSUE THREAD

**Issue by brunoqc** [SchedulesDirect/JSON-Service#34]
I'm not sure if it's a bug but I don't see where I can get the language for `MV000719340000`.

There's the `descriptionLanguage` but it seems there should be a better way. In the past there was "French" in the Genres.

I saw in https://github.com/SchedulesDirect/JSON-Service/issues/5#issuecomment-19466430 that maybe it was in the schedule but I don't find it either.

```json
{
    "airDateTime": "2014-08-10T15:35:00Z",
    "audioProperties": [
        "cc"
    ],
    "contentRating": [
        {
            "body": "USA Parental Rating",
            "code": "TVPG"
        }
    ],
    "duration": 7500,
    "md5": "wpmhoJPWz5SDHMOEoFFhNg",
    "programID": "MV000719340000",
    "videoProperties": [
        "hdtv"
    ]
}
```

**Comment by rkulagowski** [comment]
No response, closing ticket.
