### ISSUE TITLE
BUG: data is a day old

### ISSUE THREAD

**Issue by karog** [SchedulesDirect/JSON-Service#40]
Data is one day older than the XML service is providing.

Example: for USA-MA20483-X xmltvid 11463 (and others) downloaded 2014-11-13T17:12:23Z

/schedules metadata
{
    "modified": "2014-11-13T00:25:41Z",
    "md5": "TUctVEPN+Wd1PfzM2MRVMw",
    "startDate": "2014-11-12",
    "endDate": "2014-11-25",
    "days": 13
}

The modified date/time is 17 hours earlier and the start date/time is 24 hours before that.

While I work on my grabber, I am still using mythfilldatabase with the XML source and it gets one more day of data.

**Comment by rkulagowski** [comment]
API-20141201 now provides per-day schedules per-stationID up to 30 days into the future.
