### ISSUE TITLE
USA-MA20483-X only 12 days of data

### ISSUE THREAD

**Issue by karog** [SchedulesDirect/JSON-Service#45]
For all 68 stationIDs I use, today /schedules with a modified date of 2014-11-24T15:08:59Z (about 90 minutes ago) have a start date of 2014-11-24 and end date of 2014-12-07 (as it should) but the programs only go through the end of 2014-12-05 (ie an end date of 2014-12-06). Here is an example for stationID 20431 (CBS HD) showing the last program and the metadata:

        {
            "programID": "EP014145320767",
            "airDateTime": "2014-12-05T23:30:00Z",
            "duration": 1800,
            "md5": "0Eclw5nJGzCBYHIspKq1Dw",
            "new": true,
            "audioProperties": [
                "cc",
                "stereo"
            ],
            "videoProperties": [
                "hdtv"
            ]
        }
    ],
    "metadata": {
        "modified": "2014-11-24T15:08:59Z",
        "md5": "RdL8paqVi109MY3HuMMeGQ",
        "startDate": "2014-11-24",
        "endDate": "2014-12-07",
        "days": 13
    }

**Comment by rkulagowski** [comment]
API-20141201 now provides per-stationID schedules per-day, up to 30 days into the future; you no longer need to request 2, 4 or 13 days.
