### ISSUE TITLE
isPremiereOrFinale Being Populated?

### ISSUE THREAD

**Issue by kadac00** [SchedulesDirect/JSON-Service#51]
When I search the schedule for lineup USA-TX66960-X for several stations for the next 13 days I don't find any examples where the field has any value other than null.

Two recent programs that should have had this field populated are:

EP019819660001 (The Nightly Show With Larry Wilmore) which premiered on StationId 31222 (Comedy Central HD) @ 2015-01-19T04:31:00Z
EP018572320001 (Backstrom) which premieres on StationId 62420 (KTBC-DT) @ 2015-01-23T02:00:00Z

Can someone confirm that this field is indeed populated? Am I doing something wrong or did I happen to pick the two examples where the information wasn't populated upstream?

**Comment by rkulagowski** [comment]
KTBCDT is stationID 31222 (624420 is Comedy Central HD), and it's populated on the server-side as "Series Premiere":
```
{
            "programID": "EP018572320001",
            "airDateTime": "2015-01-23T02:00:00Z",
            "duration": 3600,
            "md5": "vV1B5jZsIOPkPkJe2BcTyQ",
            "isPremiereOrFinale": "Series Premiere",
            "new": true,
            "audioProperties": [
                "cc",
                "stereo",
                "DD 5.1"
            ],
            "videoProperties": [
                "hdtv"
            ],
            "ratings": [
                {
                    "body": "USA Parental Rating",
                    "code": "TV14"
                }
            ]
        },
```

Which application are you using? Does it allow you to inspect the raw JSON that's being sent from the server?

**Comment by rkulagowski** [comment]
Same for Larry Wilmore:

```
{
            "programID": "EP019819660001",
            "airDateTime": "2015-01-20T04:31:00Z",
            "duration": 1800,
            "md5": "JuAdb0mrwUp6+ELxRMGZHQ",
            "isPremiereOrFinale": "Series Premiere",
            "new": true,
            "videoProperties": [
                "hdtv"
            ]
        },
```

**Comment by kadac00** [comment]
Thank you for your help and the confirmation.  Found the problem.  There was an extra space at the end of the attribute which was causing it to not get parsed out of the JSON.

            [JsonProperty("isPremiereOrFinale ")]
            public string IsPremiereOrFinale { get; set; }

Ran a quick test of my "Coming Soon" functionality and its working now.
