### ISSUE TITLE
BUG: API 20141201: ATSC maps don't include uhfVhf physical channel

### ISSUE THREAD

**Issue by Slugger** [SchedulesDirect/JSON-Service#52]
In older apis, a channel map entry for an ATSC channel looked like this:

`{
         "uhfVhf": 11,
         "atscMinor": 1,
         "atscMajor": 11,
         "stationID": "85778"
      }`

In the new api, uhfVhf is missing.  This is required to determine the full physical tuning information for an OTA channel.  More importantly to me, I use it as a key to determine what kind of channel I'm dealing with.

**Comment by rkulagowski** [comment]
This is due to a race condition which I'm currently debugging.

**Comment by rkulagowski** [comment]
This issue should now be resolved. Please download a new lineup and confirm.

**Comment by Slugger** [comment]
Confirmed.
