### ISSUE TITLE
BUG: API 20141201: /schedules/md5 returns array for some ids

### ISSUE THREAD

**Issue by Slugger** [SchedulesDirect/JSON-Service#54]
All keys of the response are supposed to be objects, but today I'm seeing this:

https://gist.github.com/Slugger/4607bb2f85a136733c9a

And the `.dat` file (the server's response) looks like this:
```
{"80159":[],"60121":{"2015-03-15":{"code":0,"message":"OK","lastModified":"2015-03-14T14:09:39Z","md5":"XODsu09E9DyE0K4HGr1c9A"}, // And so on...
```
Notice the first entry for id 80159?  It's an array, not an object (and it's empty).  The entire response is too massive to paste in here, but send me an email if you want the whole thing, but there are dozens of those empty arrays in the response.

**Comment by Slugger** [comment]
Full response here: https://gist.github.com/Slugger/2600fcc23604633621c7

**Comment by rkulagowski** [comment]
There shouldn't be empty responses in the first place; I need to check why the server couldn't pull the MD5 for the stations that you requested because that's the root cause.

**Comment by rkulagowski** [comment]
I believe that I've found the root cause; can you try to pull again and confirm?

**Comment by Slugger** [comment]
So this now seems fixed, but I'm seeing problems again where the stationID in the responses to /schedules is once again being encoded as a number, not a string.  Again, only in a few instances, not all.

**Comment by rkulagowski** [comment]
If you can give me one or two examples where the stationID is a number and not a string then I can determine what's happening, because it shouldn't be.

**Comment by Slugger** [comment]
Looks like it's just 91308 again and that's it.

**Comment by rkulagowski** [comment]
OK, I found the error - I have a copy routine that was copying stale data (the one before the fix went in)

**Comment by rkulagowski** [comment]
Data on the server now appears valid and since the MD5s are different you should automatically download the corrected data on your next pull.
