### ISSUE TITLE
BUG: API 20141201: Lineups in status response no longer provide id

### ISSUE THREAD

**Issue by Slugger** [SchedulesDirect/JSON-Service#55]
Yesterday it worked, today the response to /status no longer includes an ID for lineups as described in:

https://github.com/SchedulesDirect/JSON-Service/wiki/Get-status

I realize this is the old api, but the new api docs are pointing to it so I assume it's still valid?

It seems the ID field was renamed to "lineup" without notice, making me think this is a bug?  The change of field name has halted my api and grabber (it expects to find the ID field as per spec).

**Comment by rkulagowski** [comment]
This is part of the standardization of using the same name for the same
thing throughout; type / transport, ID / lineup, etc.

The "DRAFT" documentation in the forum was in the process of being updated
when this ticket was opened. Once I'm sure that there aren't any other
places where the incorrect type is being returned then the documentation on
github will be updated with examples to match.

**Comment by Slugger** [comment]
Is there a link describing exactly everywhere this change is being made?  Should allow me to fix it all in one trip to the code some evening this week.

**Comment by rkulagowski** [comment]
I will check the diff and will indicate where the changes were made to the
forum.

**Comment by rkulagowski** [comment]
The message at

http://forums.schedulesdirect.org/viewtopic.php?f=17&t=2645&p=8379

now tracks the locations where this change was made.
