### ISSUE TITLE
"DELETE" of non-existent lineup in an account returns 2102, not 2103 code for API 20141201

### ISSUE THREAD

**Issue by garybuhrmaster** [SchedulesDirect/JSON-Service#56]
From a quick test case, it appears that if one tries to delete a lineup that does not exist in the account that the return code is 2102 (message: ""Invalid lineup requested. Check your COUNTRY \\/ POSTALCODE combination for validity.", which indicates (to me) that the lineup is invalid) rather than the expected 2103 (which indicates that the lineup is not in the account).

Not really a show stopper, but I was expecting (and was coding to handle) the 2103 case.

**Comment by rkulagowski** [comment]
Fixed; please confirm.

**Comment by garybuhrmaster** [comment]
Fix confirmed.  Thanks for the quick fix!
