### ISSUE TITLE
Bad Guide Data with API 20141201

### ISSUE THREAD

**Issue by GameProgramer** [SchedulesDirect/JSON-Service#60]
I switched to using the new API, and realized that at least some data returned by the new API is plain wrong. 

For Example, for Wed, 6/5, channel data for ABC (007 and 707) has "SIGN OFF" at 7 pm and 9 pm. I noticed because after I switched, the episode of Modern Family that was scheduled disappeared from my list.

**Comment by rkulagowski** [comment]
I'm getting gaps in the schedule from Gracenote; I'm investigating.

**Comment by rkulagowski** [comment]
Can you confirm if everything is good now?

**Comment by GameProgramer** [comment]
Yes, thanks, it looks good now.
