### ISSUE TITLE
API 20141201 Can't add antenna-based lineup to account

### ISSUE THREAD

**Issue by astrilchuk** [SchedulesDirect/JSON-Service#63]
I am unable to add an antenna-based lineup to my account.  I repeatedly get the following response after a long pause while calling PUT /20141201/Lineups for an antenna lineup:

{u'serverID': u'20141201.web.1', u'code': 2107, u'message': u'The lineup is being generated on the server. Please retry.', u'response': u'LINEUP_QUEUED', u'datetime': u'2015-05-18T03:24:49Z'}

Adding a satellite lineup works.

**Comment by rkulagowski** [comment]
A process had hung and a watchdog that was supposed to reset the process, didn't. I'm looking into it. Can you check if you're able to do what you need to now?

**Comment by rkulagowski** [comment]
No response, closing ticket.
