### ISSUE TITLE
Erroneous SCHEDULE_RANGE_EXCEEDED minDate and maxDate have null in  20141201/schedules 

### ISSUE THREAD

**Issue by enb141** [SchedulesDirect/JSON-Service#66]
Hi when I'm trying to get schedules in:

https://json.schedulesdirect.org/20141201/schedules

with:

[{ "stationID": "91195", "date": ["2015-09-05", "2015-09-06", "2015-09-07", "2015-09-08", "2015-09-09", "2015-09-10", "2015-09-11", "2015-09-12", "2015-09-13"] }]

I receive this response:

[{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-05","message":"Date requested (2015-09-05) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-06","message":"Date requested (2015-09-06) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-07","message":"Date requested (2015-09-07) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-08","message":"Date requested (2015-09-08) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-09","message":"Date requested (2015-09-09) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-10","message":"Date requested (2015-09-10) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-11","message":"Date requested (2015-09-11) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-12","message":"Date requested (2015-09-12) not within  ->  for stationID 91195."},{"stationID":"91195","serverID":"20141201.web.1","code":7020,"response":"SCHEDULE_RANGE_EXCEEDED","minDate":null,"maxDate":null,"requestedDate":"2015-09-13","message":"Date requested (2015-09-13) not within  ->  for stationID 91195."}]

**Comment by rkulagowski** [comment]
I know what's causing the issue; the server thinks that this is an inactive station, so it doesn't have a schedule assembled for it. I'm checking the root cause.

**Comment by enb141** [comment]
I hope you figure it out what's going on.

**Comment by enb141** [comment]
Thank you very much, now it is working again.
