### ISSUE TITLE
Spurious [] in channel lineup

### ISSUE THREAD

**Issue by MStrecke** [SchedulesDirect/JSON-Service#78]
When requesting the lineup ZZZ-28.2E-DEFAUL I get a spurious [] in the stations section at line #6411

[debug20190103.txt](https://github.com/SchedulesDirect/JSON-Service/files/2724313/debug20190103.txt)

**Comment by rkulagowski** [comment]
ZZZ lineups are now deprecated; our upstream is providing Astra in the data set.
