### ISSUE TITLE
Getting support through multiple channels has failed.

### ISSUE THREAD

**Issue by dalepres** [SchedulesDirect/JSON-Service#79]
I've emailed SchedulesDirect and I've posted on the forum.  I got no reply from the contacts page, and I submitted a post on the community forum but it has been pending moderation for about 2 weeks and not even posted.

I'm hoping this will get to someone who can help and direct me to where I can at least get a response.  

I am starting development on a new app using Schedules Direct and have an account.  I use that account with Postman in an attempt to try the JSON service APIs as a starting/learning point for my development.  I can't get past the call to https://json.schedulesdirect.org/20141201/token.  I get a 404 on that call so I can't get a token and can't do anything at all.  Testing the API from the documentation here, some of the other calls that did not require a token were working correctly.  Calls that require a token give me an error that a token is required. 

I have tried using my username and password and using my email address and password in the body as described in the documentation and neither worked - always a 404.

How do I get a token?  

Edit for clarification: I am using a SHA1 hash of my password as called for in the documentation.

**Comment by rkulagowski** [comment]
Sorry - I had rules that were moving messages but were inadvertently marking them as "read", so they weren't appearing as new messages in my sub-folder.

Please send me a direct message at rkulagow@gmail.com and we can work through your Postman issue.
