### ISSUE TITLE
stationID is now an Integer

### ISSUE THREAD

**Issue by tentious** [SchedulesDirect/JSON-Service#81]
According to the documentation: 

stationID - max 12 characters. Mandatory. This is a string, and your code must not treat it as an integer. Provides information to the grabber regarding the stationID that this schedule is for.

However, after changes/outage from yesterday, the stationID is now missing "quotes" and is now an integer. It should be string. If this is a valid change, I will need to update my application.

**Comment by rkulagowski** [comment]
This was a bug introduced in old code; stationID is now a string.
