### ISSUE TITLE
BUG: Cannot download the images for cast members

### ISSUE THREAD

**Issue by paul-h** [SchedulesDirect/JSON-Service#82]
I'm trying to download the cast images available through the API. I can get the list of available images for a cast member using the **metadata/celebrity** endpoint for example :- [https://json.schedulesdirect.org/201412 ... rity/87268](https://json.schedulesdirect.org/20141201/metadata/celebrity/87268) .

The problem is when I try to download one of the images I always seem to get a 404 page not found error although for some reason Firefox seems to think the reply is JSON and fails to parse it :?:

For example the first result from the API shows an image with a relative URI of **assets/87268_v9_ba.jpg** so I try to download from [https://json.schedulesdirect.org/201412 ... _v9_ba.jpg](https://json.schedulesdirect.org/20141201/image/assets/87268_v9_ba.jpg) which I believe should return a 303 redirect with the correct URL but I always get a 404 :?

Is the API broken, the API documentation wrong or am I doing something wrong :?:

Noticed there is a similar issue #72 but I don't see the same error just the 404 not found error message.

**Comment by rkulagowski** [comment]
This issue is resolved; the uri field in the data now points to the same scheme as is used for program images.
